name: test-clang-format

on:
  push:
    branches:
      - '*'
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: './src ./include/odometry ./include/controller ./include/hardware ./include/motions ./include/timer.hpp'
        extensions: 'hpp,cpp'
        clangFormatVersion: 17